### ISSUE TITLE
Coloca a api do plugin pra 1.0.0 a 2.2.0 

### ISSUE THREAD

**Issue by cesar6449921** [Laith98Dev/FFA#4]

**Comment by Laith98Dev** [comment]
Why you want it for a outdated api?

**Comment by ItsToxicGG** [comment]
He wants it for that api because where they live they play on old versions of minecraft to not get low fps my brasil friend told me that why they use old apis

**Comment by cesar6449921** [comment]
Yes, here in Brazil the old Minecraft versions are the best for pvp

Em dom., 3 de jul. de 2022 09:06, ItsToxic ***@***.***>
escreveu:
