### ISSUE TITLE
"Unknown dependency: BanCommands" error and crash

### ISSUE THREAD

**Issue by TheAryqn** [Laith98Dev/FFA#5]
Fix it :/
![Screenshot_20240129_203431_Samsung Internet](https://github.com/Laith98Dev/FFA/assets/128404227/fd27e285-448c-4634-a123-6e53a610768b)

**Comment by Laith98Dev** [comment]
Please use this plugin
https://poggit.pmmp.io/p/BanCommands

**Comment by TheAryqn** [comment]
> Please use this plugin https://poggit.pmmp.io/p/BanCommands

Thanks!
