### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by UnknownNull** [Laith98Dev/FFA#6]
https://www.mediafire.com/file/7sf7pntfn3zdxvy/Thu_Feb_8-14.27.58-UTC_2024.log/file

**Comment by Laith98Dev** [comment]
Are you using a fork? steps to reproduce?

**Comment by UnknownNull** [comment]
> Are you using a fork? steps to reproduce?

for softwere or plugin?

**Comment by Laith98Dev** [comment]
> PocketMine-MP version: 5.10.1+dev [Protocol 630]
Git commit: 0000000000000000000000000000000000000000

Regrading to the crashdump, i can see, you're using a PocketMine Fork, which i can't confirm the bug.

**Comment by Laith98Dev** [comment]
If you're sure, its a Bug, use a stable Pocketmine version and provide a Steps to reproduce the Bug.
